spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant_management
    username: restaurant_user
    password: restaurant_password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresSQLDialect
        format_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
